USE ERX_PROJECT -- database name
GO

IF OBJECT_ID('TB_PRODUCTS_BAR_CODES') IS NULL 
	BEGIN
		CREATE TABLE TB_PRODUCTS_BAR_CODES (
		Product_Id UNIQUEIDENTIFIER NOT NULL,
		Bar_Code_URL VARCHAR(8000) NOT NULL
		)
	END
GO
