USE ERX_PROJECT -- database name
GO

IF OBJECT_ID('TB_PRODUCTS_IMAGES') IS NULL 
	BEGIN
		CREATE TABLE TB_PRODUCTS_IMAGES (
		Product_Id UNIQUEIDENTIFIER NOT NULL,
		Image_URL VARCHAR(8000) NOT NULL
		)
	END
GO
